// <auto-generated />
using System;
using EnvanterTakip.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnvanterTakip.Migrations
{
    [DbContext(typeof(EnvanterContext))]
    [Migration("20251119125612_InitialMySqlMigration")]
    partial class InitialMySqlMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EnvanterTakip.Models.AppUser", b =>
                {
                    b.Property<int>("AppUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AppUserID"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("longtext");

                    b.Property<string>("Rol")
                        .HasColumnType("longtext");

                    b.Property<string>("Sifre")
                        .HasColumnType("longtext");

                    b.HasKey("AppUserID");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("EnvanterTakip.Models.Cihaz", b =>
                {
                    b.Property<int>("CihazID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CihazID"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("AlimTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CihazTuru")
                        .HasColumnType("longtext");

                    b.Property<string>("Durum")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("GarantiBitisTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Marka")
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.Property<string>("SeriNo")
                        .HasColumnType("longtext");

                    b.HasKey("CihazID");

                    b.ToTable("Cihazlar");
                });

            modelBuilder.Entity("EnvanterTakip.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Ikon")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Renk")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("EnvanterTakip.Models.Konum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Adres")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("Boylam")
                        .HasColumnType("double");

                    b.Property<string>("CalismaSaatleri")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double>("Enlem")
                        .HasColumnType("double");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<string>("ResimUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Konumlar");
                });

            modelBuilder.Entity("EnvanterTakip.Models.Personel", b =>
                {
                    b.Property<int>("PersonelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PersonelID"));

                    b.Property<string>("Ad")
                        .HasColumnType("longtext");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("BirimAdi")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Soyad")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefon")
                        .HasColumnType("longtext");

                    b.HasKey("PersonelID");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("EnvanterTakip.Models.Zimmet", b =>
                {
                    b.Property<int>("ZimmetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ZimmetID"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("longtext");

                    b.Property<int>("CihazID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IadeTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PersonelID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ZimmetTarihi")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ZimmetID");

                    b.HasIndex("CihazID");

                    b.HasIndex("PersonelID");

                    b.ToTable("Zimmetler");
                });

            modelBuilder.Entity("EnvanterTakip.Models.Konum", b =>
                {
                    b.HasOne("EnvanterTakip.Models.Kategori", "Kategori")
                        .WithMany("Konumlar")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("EnvanterTakip.Models.Zimmet", b =>
                {
                    b.HasOne("EnvanterTakip.Models.Cihaz", "Cihaz")
                        .WithMany("Zimmetler")
                        .HasForeignKey("CihazID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnvanterTakip.Models.Personel", "Personel")
                        .WithMany("Zimmetler")
                        .HasForeignKey("PersonelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cihaz");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("EnvanterTakip.Models.Cihaz", b =>
                {
                    b.Navigation("Zimmetler");
                });

            modelBuilder.Entity("EnvanterTakip.Models.Kategori", b =>
                {
                    b.Navigation("Konumlar");
                });

            modelBuilder.Entity("EnvanterTakip.Models.Personel", b =>
                {
                    b.Navigation("Zimmetler");
                });
#pragma warning restore 612, 618
        }
    }
}
