// <auto-generated />
using System;
using EnvanterTakip.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EnvanterTakip.Migrations
{
    [DbContext(typeof(EnvanterContext))]
    [Migration("20250814075135_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EnvanterTakip.Models.AppUser", b =>
                {
                    b.Property<int>("AppUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppUserID"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .HasColumnType("text");

                    b.Property<string>("Sifre")
                        .HasColumnType("text");

                    b.HasKey("AppUserID");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("EnvanterTakip.Models.Cihaz", b =>
                {
                    b.Property<int>("CihazID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CihazID"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<DateTime>("AlimTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CihazTuru")
                        .HasColumnType("text");

                    b.Property<string>("Durum")
                        .HasColumnType("text");

                    b.Property<DateTime?>("GarantiBitisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Marka")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("SeriNo")
                        .HasColumnType("text");

                    b.HasKey("CihazID");

                    b.ToTable("Cihazlar");
                });

            modelBuilder.Entity("EnvanterTakip.Models.Personel", b =>
                {
                    b.Property<int>("PersonelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PersonelID"));

                    b.Property<string>("Ad")
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("BirimAdi")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.HasKey("PersonelID");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("EnvanterTakip.Models.Zimmet", b =>
                {
                    b.Property<int>("ZimmetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ZimmetID"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int>("CihazID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("IadeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PersonelID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ZimmetTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ZimmetID");

                    b.HasIndex("CihazID");

                    b.HasIndex("PersonelID");

                    b.ToTable("Zimmetler");
                });

            modelBuilder.Entity("EnvanterTakip.Models.Zimmet", b =>
                {
                    b.HasOne("EnvanterTakip.Models.Cihaz", "Cihaz")
                        .WithMany("Zimmetler")
                        .HasForeignKey("CihazID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnvanterTakip.Models.Personel", "Personel")
                        .WithMany("Zimmetler")
                        .HasForeignKey("PersonelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cihaz");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("EnvanterTakip.Models.Cihaz", b =>
                {
                    b.Navigation("Zimmetler");
                });

            modelBuilder.Entity("EnvanterTakip.Models.Personel", b =>
                {
                    b.Navigation("Zimmetler");
                });
#pragma warning restore 612, 618
        }
    }
}
